// Generated by gurthang sync routes. Do not edit.
export const routes = {
{%- for route in routes %}
  {{ route.key }}: { name: '{{ route.name }}', method: '{{ route.method }}', path: '{{ route.path }}' },
{%- endfor %}
} as const

export type RouteName = keyof typeof routes

export function path(name: RouteName, params: Record<string, string | number> = {}) {
  let value: string = routes[name].path
  for (const [key, replacement] of Object.entries(params)) {
    value = value.replace(`{% raw %}{${key}}{% endraw %}`, String(replacement))
  }
  return value
}
