[package]
name = "gurthang-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Create and develop a Linux Gurthang application"

[[bin]]
name = "gurthang"
path = "src/main.rs"

[dependencies]
clap.workspace = true
gurthang-build = { path = "../gurthang-build" }
gurthang-db = { path = "../gurthang-db" }
gurthang-generate = { path = "../gurthang-generate" }
gurthang-new = { path = "../gurthang-new" }
gurthang-run = { path = "../gurthang-run" }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
tempfile.workspace = true
