[package]
name = "gurthang-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "gurthang"
path = "src/main.rs"

[dependencies]
clap.workspace = true
ctrlc.workspace = true
include_dir.workspace = true
notify.workspace = true
tempfile.workspace = true

[target.'cfg(unix)'.dependencies]
nix = { version = "0.30", features = ["signal"] }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
