// Generated by gurthang sync routes. Do not edit.
export const routes = {
  'dashboard': { name: 'dashboard', method: 'GET', path: '/dashboard' },
  'login': { name: 'login', method: 'GET', path: '/login' },
  'login.create': { name: 'login.create', method: 'POST', path: '/login' },
  'logout': { name: 'logout', method: 'DELETE', path: '/logout' },
  'register': { name: 'register', method: 'GET', path: '/register' },
  'register.create': { name: 'register.create', method: 'POST', path: '/register' },
  'welcome': { name: 'welcome', method: 'GET', path: '/' },
} as const

export type RouteName = keyof typeof routes

export function path(name: RouteName, params: Record<string, string | number> = {}) {
  let value: string = routes[name].path
  for (const [key, replacement] of Object.entries(params)) {
    value = value.replace(`{${key}}`, String(replacement))
  }
  return value
}
